digital-land/digital-land.info

- .gitignore
- dl_web/factory.py
- docker-compose.yml
- setup.py
- tests/integration/test_app.py
* Add CORS middleware
* Add test for CORS headers
* Add simple docker-compose.yml file
* Make setup.py executable and add shebang
> #1355 - Add CORS headers

- .flake8
- dl_web/.pylintrc
- dl_web/factory.py
- tests/integration/test_app.py
Trello card: https://trello.com/c/b4NUpM2h/1960-add-http-security-headers
> Add and test standard http security headers to all requests

- Makefile
- application/factory.py
- application/templates/page.cookies.html
- digital-land-frontend.config.json
- package.json
Adds cookie page and also includes updated watch task to boot.
> Add cookie page

- application/routers/dataset.py
- populate_initial_test_data.sh
- tests/integration/test_api.py
* Fix dataset.json endpoint
* Add simple script to load test data into dev environment
* This should be changed out for something more elegant at some point
> Fix dataset.json endpoint

- .env.example
- .github/workflows/continuous-integration.yml
- tests/acceptance/test_acceptance.py
To be merged once digital-land-production-collection-dataset is canonical dataset
> Repoint collection-dataset at digital-land-production-collection-dataset

- application/data_access/digital_land_queries.py
- tests/conftest.py
- tests/integration/test_api.py
See https://trello.com/c/GuKpQLUC/2173-some-https-stagingdigital-landinfo-dataset-administrative-links-return-http-code-500
> Fix 500 if no DatasetCollectionOrm result found

- .env.example
- .github/workflows/continuous-integration.yml
- tests/acceptance/test_acceptance.py
Reverts digital-land/digital-land.info#22
Need to wait till the terraform apply has been kicked off before these go in
> Revert "Repoint collection-dataset at digital-land-production-collection-dataset"

- application/core/filters.py
- application/data_access/entity_queries.py
- application/db/models.py
- application/routers/entity.py
- application/templates/entity-gone.html
- docker-compose.load-db.yml
- migrations/versions/8c9f4367ff64_add_old_entity_table.py
- tests/conftest.py
- tests/integration/test_api.py
I've only added very basic styling, if anyone has any opinions on this let me know.
> Remove and redirect entities based on the old entity table

- application/templates/entity.html
add additional if statement in the entity.html to remove geom and/or point where there is no data for those fields
> add additinoal if statement to remove empty geom

- Makefile
Depends on:
* https://github.com/digital-land/digital-land-infrastructure/pull/16
> Remove redundant Makefile targets pointing at deprecated private repo

- application/factory.py
Initial PR to set hard coded tracing at 10% of requests. This may be followed up with a PR that allows setting sample rate based on config.
More information: https://docs.sentry.io/platforms/python/guides/asgi/
> Feat: Sentry Tracing

- Makefile
- application/core/utils.py
- application/routers/entity.py
- tests/unit/core/test_utils.py
where multiple geometries are being selected pagination links only contain one of the values. use normalised parameters instead and fix this
> alter the make links function to display multiple values of one parameter

- .github/workflows/continuous-integration.yml
- Makefile
Remove makefile targets
Amend deployment makefile targets to deploy to AWS only
> Remove GOV.UK PaaS-specific functionality

- application/data_access/fact_queries.py
- application/routers/fact.py
- application/search/filters.py
- requirements/dev-requirements.in
- requirements/dev-requirements.txt
- tests/unit/routers/test_fact.py
increase unit testing by ensuring the fact routers have unit tests. very small change to code to allow None returned when response fails.
> test fact routers

- application/templates/entity.html
Change contents name, should be considered by design in the future
> update the contents header for mobile browsers

- .env.dev.docker
- .env.example
- .env.test.docker
- .github/workflows/continuous-integration.yml
- application/routers/dataset.py
- application/settings.py
- application/templates/dataset.html
Not using data subdomain any more, just path based route in CDN to S3
> Remove data file url

- application/core/templates.py
- application/templates/pages/service-status.html
- application/templates/pages/service-status.md
- application/templates/partials/footer.html
- application/templates/partials/service-status-banner.html
- assets/stylesheets/component/_service-alert.scss
Reverts banner but makes changes to make use of it again in the future.
> Revert service status banner

- application/templates/layouts/layout.html
fix issue raised by cookies removing page scripts
> make sure page scripts are included

- .gitignore
- application/templates/base.html
- application/templates/homepage.html
- application/templates/layouts/layout.html
- application/templates/partials/phase-banner.html
Removes the feedback link, 
also moved the base.html template from the digital land repo to this repo
> T 212 remove feedback button

- application/templates/pages/guidance/specifications/index.html
Ticket: [https://trello.com/c/swO6Qjsu/84-update-out-of-date-content-on-planningdatagovuk-guidance](https://trello.com/c/swO6Qjsu/84-update-out-of-date-content-on-planningdatagovuk-guidance)
Updating content on the guidance pages
> T 278 guidance

- application/templates/layouts/layout--guidance.html
ticket: [https://trello.com/c/2VlFapw1/260-remove-design-code-link-from-the-left-hand-side-of-conservation-areas-page-on-piguk](https://trello.com/c/2VlFapw1/260-remove-design-code-link-from-the-left-hand-side-of-conservation-areas-page-on-piguk
)
Before:
After:
> removed design code link from page

- assets/javascripts/base-tile-old.json
- assets/javascripts/base-tile.json
> changed the base tile set to an open source one with my personal key

- assets/stylesheets/component/_header-bar.scss
Ticket: [https://trello.com/c/oJUboyDY/369-navbar-changes-on-the-platform](https://trello.com/c/oJUboyDY/369-navbar-changes-on-the-platform)
> Move nav bar bellow page title

- application/templates/partials/phase-banner.html
MJ has requested that the sign up link opens in a new tab
Ticket: https://trello.com/c/u5ijoRnX/384-sign-up-to-take-part-in-research-link-should-open-in-a-new-tab
> link now opens in new tab

- application/templates/homepage.html
Ticket: https://trello.com/c/kYJnsJC9/391-improve-the-accessibility-of-the-homepage
> updated the home page to use better syntactical html

- application/templates/pages/service-status.html
Ticket: [https://github.com/digital-land/digital-land.info/compare/Accessability-ServiceStatus?expand=1](https://github.com/digital-land/digital-land.info/compare/Accessability-ServiceStatus?expand=1)
> remove separators from accessibility dom

- application/routers/dataset.py
- application/routers/entity.py
- application/templates/pages/docs.html
Ticket: [https://trello.com/c/VkAbB8it/396-improve-the-accessibility-of-the-documentation-page](https://trello.com/c/VkAbB8it/396-improve-the-accessibility-of-the-documentation-page)
Key changes:
- updated API endpoint descriptions.
- stop text overflow on specific size screens
- add aria labels / aria descriptions where appropriate
- update swagger url to load the p.d.g.uk api
> Accessability docs

- application/templates/components/filter-checkboxes/macro.jinja
- application/templates/partials/search-facets.html
- assets/javascripts/FilterCheckboxesController.js
- tests/unit/javascript/FilterCheckboxesController.test.js
Ticket: https://trello.com/c/XZu0KhEB/407-dataset-search-not-working-on-search-page
made the search box on the datasets filters work
> Search page: make search bar work

- application/templates/layouts/base.html
- assets/javascripts/ListFilter.js
- assets/javascripts/utils.js
Ticket: https://trello.com/c/EBBbNBj9/423-search-on-datasets-page-doesnt-seem-to-be-doing-anything
- need to write some tests (unit and acceptance) for this feature
- potential to turn the template code into a jinja macro?
> list filter now working again

- Makefile
- application/templates/partials/phase-banner.html
Accidently broke banner on homepage, this fixes that
Ticket: https://trello.com/c/g9SpANci/436-zooming-out-causes-beta-bar-to-format-incorrectly
BreakingPR: https://github.com/digital-land/digital-land.info/pull/163
> fix banner on homepage

- changeLog.md
just getting the change log up to date with recent changes that have been made
> updated change log

- assets/javascripts/MapController.js
- assets/javascripts/defaultPaintOptions.js
- tests/integration/javascript/MapController.test.js
- tests/unit/javascript/MapController.test.js
Ticket: https://trello.com/c/NLANNpU6/477-reduce-the-size-of-the-points-on-the-map
Before (Zoomed out):
Before(Zoomed in)
After Zoomed out
After Zoomed in
> changed circle radius to be a linier interpolate

- assets/javascripts/CopyrightControl.js
Ticket: https://trello.com/c/acvOPA6j/490-look-at-updating-the-os-copyright-to-clarify-its-data-is-only-for-the-base-map
> updated copyright to include basemap string

- .github/workflows/security-scan.yml
Update slack channel name & refractor old method
> Update channel name & refractor old libraries

- application/templates/components/map/macro.jinja
- assets/javascripts/LayerControls.js
- tests/integration/javascript/LayerControls.test.js
- tests/unit/javascript/LayerControl.test.js
- tests/utils/mockUtils.js
also, any url params with a key of layer will now be updated to dataset on load
> revert dataset to be the url param name instead of layer for the national map

- tests/unit/javascript/LayerControl.test.js
- tests/utils/mockUtils.js
also fixed existing false positive test
> added test for replaceRedirectParamNames

- application/templates/layouts/base.html
this is so i can access: https://search.google.com/search-console
> add google verify ownership meta tag

- application/data_access/entity_queries.py
- changeLog.md
optimizations to entity_search to reduce the impact on the database.
Testing on DEV went very well.
CPU activity is as expected, but the use of local storage is not suffering as was seen in LIVE.
The testing was based around 2 of the top 3 queries being run against the database from the web application.
> data_eng/optimize_entity_search

- .github/workflows/deploy.yml
- Makefile
- application/templates/components/entity-value/macro.jinja
- application/templates/entity.html
- application/templates/pages/guidance/introduction.md
- application/templates/partials/search-facets.html
- changeLog.md
- tests/acceptance/pageObjectModels/mapPOM.py
- tests/acceptance/test_dataset.py
- tests/acceptance/test_map.py
- tests/integration/test_api.py
- tests/integration/test_entity_search.py
- tests/test_data/entities.csv
Ticket: https://trello.com/c/xPOcvkcA/1031-add-an-e2e-test-for-using-the-map-to-find-an-entity
- Updated the map testing code to use the new map page object model
- Added commented test for the map page, to be fixed at a later date
- because this user journey was documented as part of a recent group session we did
- Added an additional entity to the test data, and fixed tests to account for this
- Fixed some accessibility issues with the entity page
- Period selected value not based of how many checkboxes checked instead of hardcoded to be 1
- Make sure datasets are in alphabetical order on the guidance pages
Note, this I'm putting the main part of this ticket on hold as the cicd doesn't seem to agree with the map and I need to do some investigation into why that is
> National map acceptance tests

- application/templates/layouts/layout--guidance.html
Ticket: https://trello.com/c/fmJjuaBI/1086-the-datasets-should-be-in-alphabetical-order
> updated dataset order

- application/templates/pages/about/about.md
- application/templates/pages/guidance/specifications/article-4-direction.md
- application/templates/pages/guidance/specifications/conservation-area.md
- application/templates/pages/guidance/specifications/tree-preservation-order.md
These are just fixing small formatting errors - mostly on the examples
> Content changes 6 Nov 2023

- application/data_access/digital_land_queries.py
- application/data_access/entity_queries.py
- application/factory.py
- application/routers/entity.py
- application/templates/components/entity-value/macro.jinja
- application/templates/entity.html
- tests/integration/test_entity_queries.py
- tests/integration/test_entity_search.py
Ticket: https://trello.com/c/IScKOoaR/1206-remove-database-interactions-that-happen-in-the-filters-in-the-view-and-add-it-to-the-controller
This ticket links the entities in the router and not using filters, ensuring logic is handled in the 'controller' and not the view
Currently deployed on dev, here is some examples of it working
https://www.development.digital-land.info/entity/7002019928
https://www.development.digital-land.info/entity/7010002550
> Entity row values to links

- application/core/filters.py
Ticket: https://trello.com/c/2pLFsPmJ/1207-get-entity-geometry-throwing-error
> updated filter to stop error if geojson is undefined

- application/templates/components/map/macro.jinja
- assets/javascripts/MapController.js
- tests/acceptance/test_map.py
the layer controls seem to have stopped appearing because the async call to load some images for the map doesn't seem to be resolving and is causing the code execution to stop
this is a hot fix, after this we should look at adding a timeout or similar to the imageloading so that this doesn't happen
> Layers controls hot fix

- application/core/filters.py
- application/core/templates.py
- application/templates/fact.html
Ticket: https://trello.com/c/IScKOoaR/1206-remove-database-interactions-that-happen-in-the-filters-in-the-view-and-add-it-to-the-controller
This ticket was to move business logic from the filters, however it turns out the only filter with BL isn't used anymore so we can just remove it
> Move logic from filters

- application/templates/pages/guidance/introduction.md
Ticket: https://trello.com/c/SVCxzPlo/1249-take-out-incorrect-content-from-guidance
> remove requested content

- application/templates/pages/about/roadmap.md
This updates the roadmap for quarter 1 (April to June) 2024. It has been produced in collaboration with team leads and our service owner, @psd. 
It contains what we'll be working on over the next 3 months. My intention is to update this roadmap once a month, or sooner where necessary. 
Please add comments or suggestions for anything I've missed that needs adding or anything that needs tweaking.
> Update roadmap for Q1 2024

- application/templates/partials/cookie-banner.html
ticket: https://trello.com/c/tvdgBqJm/1429-bug-hidecookieconfirmation?filter=member:georgegoodall8
James has found a small bug causing the hideCookieConfimation to not work. this fixes that
> make sure hideCookieConfirmation is correctly assigned to the window object

- application/templates/pages/guidance/specifications/article-4-direction.md
- application/templates/pages/guidance/specifications/conservation-area.md
- application/templates/pages/guidance/specifications/tree-preservation-order.md
> Gwen changes

- application/templates/pages/guidance/publish-data-on-your-website.md
- application/templates/pages/guidance/specifications/conservation-area.md
This reverts commit 1616a8c2ed45f1aa05b3526c76d7d7621c1b8a62, reversing changes made to a4f3aba82762ccee9cfec4dfe32e29acc62d2981.
> Revert "Merge pull request #271 from digital-land/gwencariad-patch-2"

- application/templates/pages/accessibility-statement.md
- application/templates/partials/footer.html
The department changed its name following the General Election 2024.
> Change deptartment name and link to GOV.UK

- application/templates/layouts/layout--about.html
- application/templates/pages/about/performance.html
- application/templates/pages/about/performance.md
- application/templates/partials/footer.html
Early draft for feedback. Thinking through the KPIs for our platform. 
If you’re going to build a business or national service on top of the data we index, you want to know that the platform is reliable and valuable.
> Add performance page

- application/core/utils.py
- Updated 'render' method to ensure content is a dictionary before encoding.
- Added error handling and logging.
> Fix AttributeError in DigitalLandJSONResponse

- application/core/utils.py
- application/routers/entity.py
- tests/acceptance/test_search.py
- tests/unit/routers/test_entity.py
Added condition to check the extension is passed via query parameter or path parameter.
Test cases according to the expected behavior of URL extension handling.
> Sentry attribute error fix

- application/templates/homepage.html
- application/templates/partials/mast-head.html
Ticket: https://github.com/orgs/digital-land/projects/7/views/24?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%5D&pane=issue&itemId=74898553
this ticket updates the links on the home page and nav to point to our new submit and update service
> update links to point to new submit and update service

- application/templates/pages/about/performance.md
Updated stats for end of month
> Performance 7 august 2024

- application/templates/partials/mast-head.html
The URL for the service to provide data changed. There are multiple paths for users to reach the service, but this one was missed in scoping.
Missed when scoping https://github.com/digital-land/submit/issues/285
For @paris-dp and @CharliePatterson to review.
> Fix 'Provide' URL in header

- application/templates/pages/about/roadmap.md
Updates the roadmap with our new objectives for Q3 2024.
> Update roadmap for Q3 2024

- Makefile
- package.json
This change ensure assets are copied correctly and the latest version 4 of govuk-frontend is used.
Previous versions have the old crest.
TODO - we should look at migrating to version 5 to ensure we can use the latest components.
- Ticket Link
- Closes #
> Bump GOVUK Frontend and ensure assets are copied correctly

- application/templates/pages/about/performance.md
Updated the metrics with the latest figures.
> Update the numbers

- application/routers/fact.py
This PR is about fixing the sentry unhandled Validation Error fix. Implemented a validation mechanism for the fact path and query parameters.
> Fix: Sentry ValidationError

- application/core/filters.py
This PR is for handling JSONDecodeError. This handles responses from the Ordnance Survey when non-2XX status codes are returned. 
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/3?pane=issue&itemId=83936887&issue=digital-land%7Ctechnical-documentation%7C83
> fix/sentry issue/handle-os-json-non-2xx-codes

- assets/stylesheets/application.scss
> Moving the timeline import first so its overriden

- .github/workflows/deploy.yml
- .github/workflows/deply-to-dev.yml
- assets/stylesheets/component/_timeline.scss
changing the ubuntu run version for test
> Scss fixes 1

- application/templates/homepage.html
Fixed inconsistent and confusing language on the homepage ahead of a demo.
- [ X] Bug Fix
- Ticket Link
- Closes #
> Changed word "submit" to "provide" on homepage.html to match the header and service name

- application/templates/components/entity-value/macro.jinja
PR updates the `national-park` field value link to the corresponding national-park entity on the `national-park-authority` page.
- Ticket Link: [ticket](https://github.com/orgs/digital-land/projects/9/views/14?filterQuery=-status%3A%22Ice+Box%22%2C%22Refine%2C+Prioritise+%26+Plan%22%2CBacklog%2C%22Done+-+This+Period%22%2C%22Analysis%2C+Research+%26+Design%22+team%3A%22Live+Service%22&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Labels%22%2C141075453%2C123068832%2C%22Reviewers%22%2C%22Linked+pull+requests%22%2C%22Type%22%2C%22Sub-issues+progress%22%2C%22Parent+issue%22%5D&pane=issue&itemId=95503600&issue=digital-land%7Cdigital-land.info%7C350)
on the devices and browsers this has been tested on, as well …
> Add national-park to entity link fields

- application/templates/pages/about/performance.md
- application/templates/pages/about/roadmap.md
Updating the roadmap and performance pages with the latest workstreams and performance metrics.
Reviewable at:
- https://www.development.planning.data.gov.uk/about/roadmap
- https://www.development.planning.data.gov.uk/about/performance
> Q4 24/25 update to roadmap and performance pages

- application/templates/pages/guidance/publish-data-on-your-website.md
> Data URL changed to endpoint URL

- application/templates/pages/guidance/keep-your-data-up-to-date.md
> Another 'data URL' changed to 'endpoint URL'

- .env.example
- README.md
This PR adds instructions for setting up the OS API in the development environment to the README. It also updates the `.env.example` file to include required environment variables for working with the OS API, including:
```
OS_CLIENT_KEY=
OS_CLIENT_SECRET=
DATASETTE_TILES_URL=
```
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/14?filterQuery=-status%3A%22Ice+Box%22%2C%22Refine%2C+Prioritise+%26+Plan%22%2CBacklog%2C%22Done+-+This+Period%22%2C%22Analysis%2C+Research+%26+Design%22+team%3A%22Live+Service%22&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Labels%22%2C141075453%2C123068832%2C%22Reviewers%22%2C%22Linked+pull+requests%22%2C%22Type%22%2C%22Sub-issues+progress%22%2C%22Parent+issue%22%5D&pane=issue&itemId=104286466&issue=digital-land%7Cdigital-land.info%7C36 …
> OS API setup guide

- application/templates/pages/guidance/specifications/conservation-area.md
> added presumption to publish content

- application/data_access/entity_queries.py
- application/routers/entity.py
- tests/integration/test_entity_queries.py
This PR addresses an issue where `article-4-direction-area` entities incorrectly link to` article-4-direction `entities belonging to a different organisation. The solution updates the `dataset` parameter to `organisation_entity` in `lookup_entity_link() `and adds a condition to ensure the `organisation_entity` matches. 
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/14?filterQuery=-status%3A%22Ice+Box%22%2C%22Refine%2C+Prioritise+%26+Plan%22%2CBacklog%2C%22Done+-+This+Period%22%2C%22Analysis%2C+Research+%26+Design%22+team%3A%22Live+Service%22&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Labels%22%2C141075453%2C123068832%2C%22Reviewers%22%2C%22Linked+pull+requests%22%2C%22Type%22%2C%22Sub-issues+progress%22%2C%22Parent+issue%22%5D&pane=issue&itemId=102680452&iss …
> updated lookup_entity_link() param

- application/templates/pages/about/about.md
This fixes some statements on the About page to make them more factual.
> Update copy following comments from Policy

- .github/workflows/deply-to-staging.yml
> Deploy to staging yml

- application/db/session.py
- application/factory.py
This PR address the [OperationalError](https://planning-data-platform.sentry.io/issues/6186256055/events/4e2dc3f18bcf4dfd9103948c27b5f650/?project=4506540992626688) raised in sentry. The solution includes adding a retry logic and enabling `pool_pre_ping` to keep database connections alive.
- Ticket Link: [ticket](https://github.com/orgs/digital-land/projects/9/views/14?filterQuery=-status%3A%22Ice+Box%22%2C%22Refine%2C+Prioritise+%26+Plan%22%2CBacklog%2C%22Done+-+This+Period%22%2C%22Analysis%2C+Research+%26+Design%22+team%3A%22Live+Service%22&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Labels%22%2C141075453%2C123068832%2C%22Reviewers%22%2C%22Linked+pull+requests%22%2C%22Type%22%2C%22Sub-issues+progress%22%2C%22Parent+issue%22%5D&pane=issue&itemId=97238542&issue=digital-land%7Ctechn …
> Fix:sentry issue: OperationalError

- application/templates/pages/guidance/open-digital-planning-community.md
> Update ODP links

- application/templates/pages/guidance/specifications/listed-building.md
Update to LBO Guidance to match changes in technical specification - removal of `document-url` and `listed-building-grade`
> Update LBO Guidance

- application/templates/partials/mast-head.html
- tests/acceptance/test_organisation.py
Add organisations link to header
https://github.com/digital-land/digital-land/issues/403
> Add Organisations link to header

- application/templates/national-map.html
Add OS maps terms and conditions
https://github.com/digital-land/digital-land/issues/409
> Add OS maps terms and conditions

- .env.example
- application/settings.py
- application/templates/components/map/macro.jinja
- application/templates/national-map.html
Add a new TILES_URL option to use instead of DATASETTE_TILES_URL when we want to switch to the new version
- Ticket Link
- Closes #
> add optiona TILES_URL to use the new tilles url

- application/templates/partials/feedback.html
- application/templates/partials/phase-banner.html
- tests/acceptance/test_dataset.py
Update Google form link to Microsoft forms
- Ticket Link
- Closes #406 
> Update Google form link to Microsoft forms
