.flake8
Makefile
README.md
application/core/models.py
application/data_access/entity_queries.py
application/search/filters.py
docker-compose.load-db.yml
docker-compose.yml
gunicorn_conf.py
prestart-dev.sh
requirements/dev-requirements.in
tests/integration/test_entity_search.py

* When `field` querystring parameter is present (at leaset once), the only fields returned will be those specified in one of the `field` querystring arguments.
* Also added make target to load data from `digital-land-production-collection-dataset` using `digital-land-postgres`
* Fix prestart script execution in dev by removing `CMD` override, allowing [parent docker image `CMD`](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/start.sh#L23) to execute `$PRE_START_PATH`

#2204 Add `field` parameter to specify fields returned from API

---

application/exceptions.py
application/factory.py
application/search/filters.py
tests/integration/test_api.py
tests/integration/test_entity_search.py

If it doesn't, return a nice helpful validation message with a list of datasets that do exist
Trello Card: https://trello.com/c/82Ldl1Fu/2260-for-entity-endpoint-when-dataset-argument-specified-validate-values-exists-and-return-error-if-not
If anyone's got any thoughts as to why the dataclass validator exceptions aren't being reraised as `RequestValidationError` rather than `ValidationError` (see [here](https://fastapi.tiangolo.com/tutorial/handling-errors/#override-request-validation-exceptions) for the difference) then i'm all ears

Validate that dataset given in querystring argument exists

---

.env.example
.env.test.docker
.github/workflows/continuous-integration.yml
Makefile
application/routers/dataset.py
application/search/enum.py
application/search/filters.py
application/settings.py
application/templates/dataset.html
tests/integration/test_api.py

Trello Card: https://trello.com/c/lTxje8xi/2228-flatten-the-json-fields-so-that-they-are-all-top-level-values
* Exposes a `/dataset/{dataset name}.csv/link` endpoint which returns a 302 response redirecting to hoisted CSV
* IF `dataset_name` does not exist, or has `typology=specification` an HTTP error code will be returned

Add API to redirect to hoisted CSV file

---

.env.dev.docker
.github/workflows/continuous-integration.yml
Dockerfile
Makefile
application/factory.py
application/settings.py
manifest.yml
migrations/env.py

* Support `DATABASE_URL` if it exists, use to populate `WRITE_DATABASE_URL` and `READ_DATABASE_URL` in settings
* gov.uk PaaS provides `DATABASE_URL` to app environment where that app is provisioned with a postgres backing service
* string replacement is necessary due to SQLAlchemy deprecating `postgres://` protocol specifier in favour of `postgresql://`. See [here](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-3687655465c25a39b968b4f5f6e9170b) for details
* Modify healthcheck response so that the app returns 200 when started on unpopulated database. 
* Needed to successfully start app on gov.uk PaaS
* Returns the presence of entities as a parameter
* Separate PR to modify healthcheck to check this parameter and alert on missing entities …

Support DATABASE_URL if it exists, for compatability with gov.uk PaaS

---

assets/javascripts/dl-national-map-controller.js

there's a lot of data that isn't named in the source data. For these the map doesn't link through as there's no text to attach a hyperlink to. I have added an if clause to check for this in the map controller js. it fills in Not Named as a value, this should be easy change if we want to replace it with a different field in the future.

add not named to map where entities are not named

---

application/factory.py

previous update broke some of the tests and we are changing some responses. this was majority fixed by including a json response to both geojson and json requests. there is only a HTML response when these extensions are not included.

alter code to include geojson in json responses to validation

---

.dockerignore
Dockerfile
Makefile
application/factory.py
application/settings.py

*What?*
* Bake the short commit hash into docker images.
* Use the baked-in commit hash as the release tag in sentry.
*Why?*
So when exceptions show up in sentry and changes in performance show which change they are related to.

Feat: sentry release logging

---

application/data_access/fact_queries.py
application/routers/fact.py

add retries to bad requests form datasette, this should help stop requests from timing out. Altered the dataset fields query to take an entity as an optimal parameter. This speeds up the query but we may want a more permanent solution for retrieving dataset field names.

alter fact queries to be more defensive

---

Makefile

`CF_BASE_APP_NAME` was being referenced by non-cloudfoundry specific functionality, have readded it as `DL_APP_REMOTE_NAME`

Readd parameter to makefile

---

application/templates/dataset.html

what?
update links on dataset page so they lead to the correct place.
why?
in the change of infrastructure the folder contianing the relevant data may have moved, hence we need to reflect this.

update links from data to dataset

---

Makefile
application/factory.py
assets/robots.txt

We don't have a robots.txt file which can be used to ask search engine crawlers to exclude certain parts of the web sire. We've been seeing page fetches for rows in the 500,000 range which are almost certainly crawlers that we want to discourage for now.
This change adds a couple of paths in our sub site from being crawled. See the Disallow entries in robots.txt.
There may be more sections we want to exclude. Please comment appropriately and I'll add them.
There's away of testing this stuff but it requires adding custom files to the site for google/bing to confirm site ownership. We can have a look at that at some point.

Add robotx.txt exclusions

---

application/factory.py

My initial cut of the robots.txt server route did not explicitly tell Fast API to exclude it from application API schema.
This update
1.  Explicitly excludes robots.txt from the schema generation
2. Moves the route to the base routes served by the application.
The first change has the effect of fixing the reported defect. Screenshot below.
Next step: Add the `https://www.planning.data.gov.uk/openapi.json` path to the Canaries checker.

Update how robots.txt is served - exclude it from Fast API

---

requirements/dev-requirements.txt
requirements/requirements.txt
tests/acceptance/test_acceptance.py

Tests checks if the Documentation page has loaded with HTTP status 200 or if the Documentation page has loaded with an error message(verified by regenerating the error occurred earlier).
Reports error in case of status other than 200 with suitable error message
Playwright version updated to use expect() function.

Documentation page status check

---

application/templates/components/map/macro.jinja
tests/acceptance/test_entity.py

Ticket: [https://trello.com/c/yVxlUc96/75-add-playwright-test-for-maps-that-went-missing](https://trello.com/c/yVxlUc96/75-add-playwright-test-for-maps-that-went-missing)
added two tests one to check the search page, the other to check the entity page.
this will probably be rewritten/modified once we have some user stories to base these tests on. (see that ticket [here](https://trello.com/c/R9Y6pwdb/186-add-acceptance-tests-to-didgital-landinfo))

75 add playwright test for maps that went missing

---

.github/workflows/deploy.yml
.github/workflows/deply-to-dev.yml
.github/workflows/security-scan.yml
Dockerfile
application/core/templates.py
application/data_access/entity_queries.py
application/db/models.py
application/factory.py
application/routers/about_.py
application/routers/curie.py
application/routers/dataset.py
application/routers/entity.py
application/routers/fact.py
application/routers/guidance_.py
application/search/filters.py
requirements/dev-requirements.in
requirements/dev-requirements.txt
requirements/requirements.in
requirements/requirements.txt
tests/acceptance/test_acceptance.py
tests/integration/test_api.py
tests/integration/test_entity_search.py
tests/integration/test_search_invalid_entities.py
tests/unit/search/test_validators.py
tests/unit/test_pagination.py

Ticket: (https://trello.com/c/VVq7jid3/297-fix-pip-requirement-for-pdguk)[https://trello.com/c/VVq7jid3/297-fix-pip-requirement-for-pdguk]
after clearing all my installed pip packages and rerunning [p.d.g.uk](http://p.d.g.uk/) it turns out that some requirements are missing, this PR adds required packages to the requirements.in file. it also specifies a version of fast api. as the latest version of fastapi isn't compatible with our code.
also, I have removed the import of dl-frontend.globals.random. and instead just included this function directly
After first putting this PR up, the tests and linting was failing due to numpy 1.25.1 being unsupported with python 3.8. 
also, some linting work was done so the linting checks pass

fix dl.info requirements

---

application/templates/components/phase-banner/macro.jinja
application/templates/homepage.html
application/templates/layouts/base.html
application/templates/partials/phase-banner.html
assets/stylesheets/component/_header-bar.scss
assets/stylesheets/component/hero/_hero.scss

Ticket: [https://trello.com/c/a2eAW0QS/367-banner-changes-on-the-platform](https://trello.com/c/a2eAW0QS/367-banner-changes-on-the-platform)
updated the banner color and text
----------------------------------
----------------------------------
----------------------------------
Navigating the jinja templates was far more complicated that it should be. a lot of refactoring can be done here. for the base templates

updated banner

---

application/templates/pages/about/about.md

Ticket: https://trello.com/c/ycMjt4t9/392-improve-the-accessibility-of-the-about-page-and-roadmap-page
Accessibility Checks: 
1. Ensure there is a hidden link at the top of the page that is the first tabbable element, that is a skip to main content link: Yes
2. Ensure you can tab forward through all clickable sections
3. Making sure all links are correctly highlighted when tabbed to: Yes
4. Make sure links exist to skip navigation elements, these links should be hidden as they should only be accessible via screen readers: Yes
5. Ensure you can tab backwards through all clickable sections, and there aren’t any keyboard traps: Yes 
6. Open the screen reader, navigate through the page using the screen reader. Checking for any major issues: No obvious issues
7. If any pop ups are used on this …

took separators out of accessibility dom

---

application/templates/partials/cookie-banner.html
assets/javascripts/cookies.js

Ticket: [https://trello.com/c/zT4Mqp56/424-disabled-javascript-causes-cookie-popup-to-remain-open](https://trello.com/c/zT4Mqp56/424-disabled-javascript-causes-cookie-popup-to-remain-open)
The cookie banner was appearing when js is disabled. you then also couldn't close it. 
this has now been rectified.

cookie banner no longs appears when JS is disabled

---

application/templates/partials/phase-banner.html

Ticket: https://trello.com/c/g9SpANci/436-zooming-out-causes-beta-bar-to-format-incorrectly
the beta banner on the map page was styled incorrectly when zooming out

fixed beta banner styling

---

assets/javascripts/MapController.js
tests/integration/javascript/MapController.test.js
tests/unit/javascript/MapController.test.js
tests/utils/mockUtils.js

Ticket: [https://trello.com/c/EuG6jsW0/389-bug-fix-mouse-events-on-feature-popups](https://trello.com/c/EuG6jsW0/389-bug-fix-mouse-events-on-feature-popups)
Using the mouse wheel when hovering over a feature popup would initiate a scroll action. this was jarring and has been removed for accessibility

popup now doesn't have a scroll event handler

---

application/templates/components/map/macro.jinja
application/templates/pages/guidance/introduction.md
assets/javascripts/LayerControls.js
assets/javascripts/MapController.js
assets/javascripts/defaultPaintOptions.js
assets/stylesheets/component/map/scss/_side-panel.scss
tests/integration/javascript/LayerControls.test.js
tests/unit/javascript/LayerControl.test.js
tests/utils/mockUtils.js

Ticket: https://trello.com/c/TQNpHx0L/430-national-map-layers-components-not-showing-up-in-full-screen
The layerControls panel isn't a proper maplibre component. so when full screening the map the component disappears
We should change this to be an official maplibre component 
- converted the layer controls map overlay to be a maplibre component. (by using the interface methods onAdd/onRemove)
- rewrote tests to work with new code
- removed the #monitoring sting from the end of the link on the guidance page 
- added a mock function to the maplibre mock object for moving layers to tidy up the test console of error messages
- moved default paint options into its own file to be reused
- We should look at making the layer controls component more accessible
- - this could be done as part of a …

Layer controls

---

assets/javascripts/LayerControls.js

it seems that a dataset without paint options is being loaded. 
I've added some code that ensures that the default colour and opacity are used if this is the case

Fix the map code

---

changeLog.md

added the following entry to the changelog
- Updated circle radius on the map to interpolate between 8 and 0.8 based on zoom level
- Feature layers on the map now have a cursor pointer when hovered over
- OS copyright updated to specify Basemap contains OS data &copy; Crown copyright and database rights
- Zoom and centre now gets added to the url for the map, and when navigating back to the map page the map will be zoomed and centred to the previous location
- Smaller circles on the map are easier to see
- The cursor pointer makes it more obvious that the feature is clickable
- To avoid people thinking that our data is owned by OS
- To make it easier to share a specific location on the map
***
<br />

updated changelog

---

assets/javascripts/MapController.js

https://trello.com/c/iFEbQKfH/478-minimum-zoom-should-show-all-of-england-including-on-large-screens-ie-4k
- Changed the default viewport and zoom level of the map to make sure all of england is visible (tested on screen sizes up to 4k)
- We want to ensure all of england is visible on the map
- we should look at getting the European continent on the map, as the os map only shows some of the coastline

whole of england now shown by default up to 4k

---

application/templates/homepage.html
application/templates/national-map.html
application/templates/pages/accessibility-statement.md
changeLog.md
tests/acceptance/test_acceptance.py

- Updated the title for the map to 'Map of planning data for England'
- To make it clear that the map is only for England
- https://trello.com/c/HFknCyRA/439-make-it-apparent-where-the-site-is-for-national-map-isnt-clear

updated the title of the map to 'Map of planning data for England'

---

application/templates/components/hero/macro.jinja

as part of a previous commit I replaced the breadcrumbs for a back button across the site, this should have been removed on the homepage instead

remove back button from homepage

---

assets/javascripts/MapController.js
changeLog.md

Ticket: https://trello.com/c/yJVIlzjn/752-investigate-the-pan-and-zoom-controls-crashing-on-some-devices
Problem statement: The map on some mobile browsers seems to be crashing after some time
- Fixed panning issue on the map page by changing the handlemove to only be called on moveend instead of move
- because this was causing the map to crash on some browsers
- updated the changelog format to make it consistent

Fix scrolling issue on map

---

application/templates/pages/guidance/how-to-provide-data.md
application/templates/pages/guidance/introduction.md
application/templates/pages/guidance/specifications/article-4-direction.md

Article 4 ‘has a permitted development right’ changed to 'withdraws a permitted development right'
Put list of data subjects/planning considerations into alphabetical order on how to provide page
A couple of RIPA references removed from intro page

Content changes 26 oct23

---

application/data_access/entity_queries.py
application/search/filters.py

We currently quote in our documentation that the default spatial_relation used is within. This is incorrect and we have different defaults based on the parameters that someone uses

apply spatial relation to curie geom queries

---

application/templates/components/entity-value/macro.jinja

Turn local-authority-district and local-planning-authority and parish references into links, 
eg https://www.planning.data.gov.uk/entity/46 should link to https://www.planning.data.gov.uk/prefix/local-authority-district/reference/E07000129 
but we don't have a lookup so have made it https://www.planning.data.gov.uk/prefix/statistical-geography/reference/E07000129 
There's a lot of hard-coding here we should be able replace with inference and configuration in the specification.

Turn LAD, LPA and parish references into links

---

application/templates/homepage.html
application/templates/partials/phase-banner.html

Can't share ticket as trello is down
this PR was requested by Adam. it removes the boarder from the phase banner on the home page and also ensures that the link in the phase banner has the correct govuk-link classname

removed boarder from phase banner on home page

---

application/core/filters.py
application/core/models.py
application/core/templates.py
application/templates/components/entity-value/macro.jinja

this PR was causing some issues, and needs redoing anyway as as part of this ticket : https://trello.com/c/IScKOoaR/1206-remove-database-interactions-that-happen-in-the-filters-in-the-view-and-add-it-to-the-controller
so for now we will revert this and pick up the new ticket later this week
Broken on prod: https://www.planning.data.gov.uk/entity/7002000975
Fixed on dev: https://www.development.digital-land.info/entity/7002000975

Revert "Entity row values to links"

---

application/templates/pages/about/roadmap.md

It's good practice for a user-facing roadmap to show when it was last updated, as this communicates to users how fresh or stale the information is. For example, see the [GOV.‌UK Design System roadmap](https://design-system.service.gov.uk/community/roadmap/).

Add last updated date to roadmap

---

application/templates/pages/about/roadmap.md

Removing the Kramdown block attributes, e.g. `{:target="_blank"}`, because those aren't parsed.
This fixes issues in #251 which I noticed on the [roadmap on staging](https://www.staging.digital-land.info/about/roadmap). It [wasn't deployed to production](https://github.com/digital-land/digital-land.info/actions/runs/8665593718/job/23764799272) which allowed us to catch these.

Remove Kramdown block attributes

---

application/routers/entity.py
application/templates/entity-gone.html
tests/integration/test_api.py
tests/unit/routers/test_entity.py

Reference ticket: https://trello.com/c/MNP2L46O/1405-bug-410-responses
- Returns status code 410 instead of 200 for 'Entity removed' page
- Added case for returning json response for 410s when called with .json extension
- Changed the html page content/design for 410 to match other error pages
- Updated test cases to reflect the changes

Adding json response for 410 when triggered with extension .json

---

application/templates/pages/about/roadmap.md

This was on my task list for the week, but coincidentally the folks at [Public Digital posted a blog post about public backlogs and open roadmaps today](https://public.digital/pd-insights/blog/2024/07/filling-in-the-gaps-the-case-for-public-backlogs-roadmaps). It felt like the right time to update our roadmap following setting Q2 OKRs.
I've also included links to our [data design backlog](https://design.planning.data.gov.uk/what-we-are-working-on). Once we've populated the roadmap for the [service for data providers](https://check.planning.data.gov.uk/), I'll add that too (it'll be [on GitHub](https://github.com/orgs/digital-land/projects)).

Add Q2 2024 roadmap

---

application/templates/organisation_index.html

currently the organisation page uses curies to link to organisation entities. The problem with this is that the wrong prefixes are being used as some datasets have wikidata prefixes because the references are taken from wikidata. 
Currently the application doesn't have the logic or information to understand what prefixes should be used so instead we'll switch them to using links which reference the entity directly.

change href to entity

---

application/data_access/entity_queries.py
tests/conftest.py
tests/integration/data_access/test_entity_queries.py

A PR which reinstates calculating the count over groups and adds two specific tests cases which have to pass in our platform. They are integration tests to test the query logic when geometry_reference params are passed in.
[Trello Ticket](https://trello.com/c/ftAYCgOP/3378-bug-difference-in-counts-on-platform)

add tests and revert count to use the historic way that worked.

---

application/templates/components/entity-value/macro.jinja

This is a fix for: https://github.com/digital-land/digital-land.info/pull/270
Moved the split and rendering of document urls to the catch all section of macro.
The original implementation was in section that expected a field_spec, which in the actual call was None, therefore the rendering in really fell into the last else block which just rendered the content as a single string.

Fix for document-urls being rendered as links

---

application/templates/pages/guidance/specifications/article-4-direction.md
application/templates/pages/guidance/specifications/conservation-area.md
application/templates/pages/guidance/specifications/listed-building.md
application/templates/pages/guidance/specifications/tree-preservation-order.md

A user at an LPA raised the following query.
> A few weeks ago, I was invited to participate in testing for the four planning datasets that the government plans to publish. I have identified an issue that I would like to bring to your attention. While we successfully uploaded a .CSV file as a user, it was communicated that this method is not the preferred approach. Instead, using a REST API seems to be the better option. However, upon reviewing the technical documentation, I noticed that many of the column headers contain hyphens (-), which are not supported in the ESRI ecosystem. Here’s a link below; it’s something I would have never considered using within a header name.
>
> https://digital-land.github.io/specification/specification/article-4-direction/
>
> What characters should not be …

Add guidance on the field names we accept

---

application/templates/partials/mast-head.html
tests/acceptance/test_acceptance.py
tests/acceptance/test_documentation.py

I keep being asked if we have an API, so changed the "Documentation" top link to be "API".
Also, added a headline link to "Design data" which was missing.

Top links to API and Design data

---

docker-compose.security.yml

Change version of app to latest when performing security scanning
Docker compose configuration for security scanning was referencing a version of the frontend from around 2 years ago.
- Ticket Link: https://trello.com/c/7mOAVwFo/3443-address-high-priority-security-issue-on-digital-land-platform
Run the security scan GitHub workflow.

Fix: Use current version of app in security scanning

---

.env.dev.docker
.github/workflows/security-scan.yml
assets/stylesheets/application.scss
default.paths.json
docker-compose.security.yml
docker-compose.yml
package-scripts.js
package.json

Corrected Docker Compose setup for Security Scanning by tweaking environment variables and volume mounts.
Also added call to `make frontend` to the Security Scanning GHA workflow to ensure static resources are generated prior to running the docker compose setup.
- Ticket Link: https://trello.com/c/7mOAVwFo/3443-address-high-priority-security-issue-on-digital-land-platform

Fix for Trello #3443: Corrected Docker Compose setup for Security Scanning

---

application/templates/homepage.html

- fixes broken URL and change title to reflect new naming
- move submit block above data design block to reflect priority — as discussed with @gwencariad and @colmjude

Update submit name and move block above data design

---

application/core/filters.py

This PR is for a security issue identified by the security scanner, a high priority issue related to the use of weak SHA-1 hashing for security purposes in our codebase. SHA-1 is considered insecure for cryptographic operations. SHA-1 is used in the codebase for cache-busting, which is not a security-sensitive task. To prevent the security scanner from flagging this as a vulnerability, we explicitly set `usedforsecurity=False` in all instances where SHA-1 is used for non-security tasks.
- Ticket Link: https://trello.com/c/ZjV6TnPG

fix: set hashlib's usedforsecurity=False to prevent weak hash

---

application/data_access/entity_queries.py
tests/integration/test_entity_queries.py
tests/unit/data_access/test_entity_queries.py

This PR addresses a critical bug in the "Period" filtering logic for search entities. The filtering system incorrectly returned current entities when the "Period" filter was set to "Historical", leading to inaccurate search results.
Updated the `_apply_period_option_filter` function to ensure that historical entities only include those with a past end-date and that current entities either have no end-date or a future end-date.
- Ticket Link: https://trello.com/c/yoFWARjV

Bug Fix: Historical Entity Filtering Bug

---

Makefile

Refactor Makefile to copy GOVUK Frontend assets correctly. Previously the assets were being copied into the `govuk` folder rather than `govuk/assets`.

Refactor Makefile to copy GOVUK Frontend assets correctly

---

assets/javascripts/MapController.js

- [Bug Fix
The base map seems to disappear bellow a zoom level of 6. after spending two mornings looking I can't find any recent commits made, or anything local that would restrict this. 
my guess is os maps have done something to restrict this on their end
for now, ive updated our code, to set the min zoom level to 6. 
deployed to dev and all seems to work now
https://www.development.digital-land.info/map

Update min zoom

---

application/templates/pages/about/performance.md
assets/javascripts/PerformancePage.js

Add Dataset Chart to Performance page
- Ticket Link
- Closes #

Add Dataset Chart to Performance page

---

application/routers/curie.py
tests/acceptance/api_contract/__init__.py
tests/acceptance/api_contract/test_curie_route.py
tests/acceptance/api_contract/test_entity_route.py

When accessing data as a curie you are redirected to an entity. Currently you cannot provide an extension so curie information is not available as a json.
- Ticket Link
- Closes #
Check that curie route can be returned as a json. Also check that the normal route still works.

add extension to curie route

---

application/templates/pages/guidance/specifications/local-plan.html
application/templates/pages/guidance/specifications/local-plan.md

Need to add a `.html` file for every new specification guidance page we create
- Ticket Link
- Closes #

Add template file for local plan guidance

---

application/templates/pages/guidance/specifications/index.html
application/templates/pages/guidance/specifications/local-plan.md

Bullet lists from markdown not showing because need a new line between. Fixed in this commit
- Ticket Link
- Closes #

fix formatting issues with markdonw

---

.github/workflows/deploy.yml
.github/workflows/deply-to-dev.yml
application/db/session.py
application/settings.py
migrations/env.py

We are getting a lot of TimeoutError errors due to 'QueuePool limit of size 5 overflow 10 reached'. For this, we have increased the pool size and the max_overflow size.
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/3?pane=issue&itemId=83936590&issue=digital-land%7Ctechnical-documentation%7C80

Adding  pool size and max overflow for timeout issue

---

application/factory.py
application/templates/layouts/layout--about.html
application/templates/pages/about/contact.html
application/templates/pages/about/contact.md
application/templates/pages/cookies.html
application/templates/pages/terms-and-conditions.html
application/templates/pages/terms-and-conditions.md
application/templates/partials/footer.html
tests/accessibility/test_accessibility.py

This pull request adds a terms & conditions page, plus contact details. 
The terms & conditions have been checked by Government Legal Department. The terms make clear the conditions of use, that we do not accept any liability or provide any warranty for use of the data or the website, and that much of the data we index is provided by other sources. It also makes clear the licences and licence conditions associated with the data and the service.
These terms do not establish any service-level agreements for the API, but that is something we can do in future. 
Also introducing a Contact page, and have made changes to the Cookies page to make it more accurate.
Available for checking on https://www.development.planning.data.gov.uk/
_We encourage you to keep the code coverage percentage at 80% …

Add terms and conditions, plus contact page

---

.github/workflows/deploy.yml
.github/workflows/security-scan.yml
application/core/filters.py
application/templates/entity.html

Frontend changes to deal with page loads for complex heavy geometries.
- Ticket Link: https://github.com/orgs/digital-land/projects/9/views/3?pane=issue&itemId=93171235&issue=digital-land%7Ctechnical-documentation%7C210
- Closes #

Complex geometries issue fix: PART 1 - Frontend Changes

---

application/templates/pages/service-status.html

We've had several emails from people trying to use Companies House services but getting 5XX errors. It turns out that if you google `companies house service status`, our service status page is the second result.
I've added some content to our service status page that hopefully makes it clear that we're the Planning Data service, and it points users to other contact routes if they've ended up in the wrong place.

Make clear which service we are

---

application/templates/pages/guidance/specifications/conservation-area.md
application/templates/pages/guidance/specifications/local-plan.md

Following the [migration of dataset-editor](https://github.com/digital-land/technical-documentation/issues/319), this PR updates LPA-facing documentation to help them pick document type codes.

Update links to document types finder in Dataset Editor

---

application/data_access/digital_land_queries.py
application/routers/map_.py
tests/integration/test_digital_land_queries.py

Another easy performance win for frequently visited page: the `get_datasets_with_data_by_typology` (always called with "geography" param).
- Closes #383

cache `get_datasets_with_data_by_typology(sesssion, "geography")` calls

---

application/data_access/entity_queries.py
application/routers/entity.py

We have noticed that entity linking for Conservation Areas and Listed Buildings is not working as expected. For Conservation Areas, this is because the field was not added to the EntityLinkField list.
For Listed Buildings, a code change to the function was required in order to bypass the organisation check that was brought in via #388. We need to continue to limit by organisation for all other datasets, but for Listed Building it must search for the correct LB from the Historic England data (which has a different organisation). For ease, I have changed to code to only search by reference and dataset for listed building. This represents minimal risk as the only source of listed building data is Historic England - however, we may want to refactor this code at a later date to remove the …

Fix broken entity linking
